# Dependencies
markdown:         kramdown
highlighter:      pygments
plugins:
        - jekyll-paginate
        - jekyll-gist
paginate: 5
paginate_path: "page:num"

# Permalinks
permalink:        pretty

# Setup
title:            Yuan SHANG
tagline:          'My personal page'
description:      'Bioinformatician in University of Arizona'
url:              https://github.com/RaymondSHANG/RaymondSHANG.github.io/
baseurl:          /

author:
  name:           'Yuan SHANG'
  url:            www.linkedin.com/in/yuanshang2020

paginate:         5

# Custom vars
version:          2.1.0

github:           
  repo:           https://github.com/poole/hyde
