# Dependencies
markdown:         kramdown
highlighter:      pygments

paginate: 5
paginate_path: "page:num"

# Permalinks
#permalink:        pretty

# Setup
title:            Yuan SHANG
email:            yshang@email.arizona.edu
tagline:          'My personal page'
description:      'Bioinformatician in University of Arizona'
url:              /
baseurl:          /

author:
  name:           'Yuan SHANG'
  url:            www.linkedin.com/in/yuanshang2020
  github:         https://github.com/RaymondSHANG

paginate:         5

# Custom vars
version:          1.0.0